import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-oilfield-service-ticket-invoice-audit",
  "engine": "recovery",
  "title": "Oilfield Service Ticket & Invoice Audit",
  "shortTitle": "Oilfield Service Ticket and Invoice Audit",
  "tagline": "Validate oilfield service invoices against signed field tickets, crew and equipment time, rate sheets, and job scope.",
  "industry": "Oilfield Spend Recovery",
  "buyer": "Exploration and production operators",
  "uiPort": 4713,
  "apiPort": 5713,
  "accent": "#0369a1",
  "currency": "USD",
  "primaryOutcome": "Oilfield Service Ticket & Invoice Audit converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect master service agreements, wells, work orders, field tickets, crews, equipment, materials, rates, standby, mileage, invoices, and credits in one accountable workflow. Validate oilfield service invoices against signed field tickets, crew and equipment time, rate sheets, and job scope.",
  "calculation": {
    "actualKey": "chargedAmount",
    "expectedKey": "supportedAmount",
    "actualLabel": "Charged or Paid Amount",
    "expectedLabel": "Evidence-Supported Amount",
    "varianceLabel": "Potential recovery or avoided cost",
    "direction": "actual-minus-expected",
    "finding": "Oilfield Service Ticket & Invoice Audit evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("master-service-agreement-library","OST01","Master service agreement library","Execute master service agreement library using master service agreements, wells, work orders, field tickets, crews, equipment, materials, rates, standby, mileage, invoices, and credits.","Produce a governed master service agreement library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Vendor / Well Job","text","Vendor / Well Job · Standard Case"],["caseReference","Master service agreement library Reference","text","OST01-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1470000],["supportedAmount","Evidence-Supported Amount","currency",1234800],["domainDriver","Service Category","select","Drilling",["Drilling","Completion","Well service"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Master service agreement library case","Well job registry case","Work order ingestion case","Field ticket capture case","Crew hour validation case"]}),
feature("well-job-registry","OST02","Well job registry","Execute well job registry using master service agreements, wells, work orders, field tickets, crews, equipment, materials, rates, standby, mileage, invoices, and credits.","Produce a governed well job registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Vendor / Well Job","text","Vendor / Well Job · Standard Case"],["caseReference","Well job registry Reference","text","OST02-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1470000],["supportedAmount","Evidence-Supported Amount","currency",1234800],["domainDriver","Service Category","select","Drilling",["Drilling","Completion","Well service"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Master service agreement library case","Well job registry case","Work order ingestion case","Field ticket capture case","Crew hour validation case"]}),
feature("work-order-ingestion","OST03","Work order ingestion","Execute work order ingestion using master service agreements, wells, work orders, field tickets, crews, equipment, materials, rates, standby, mileage, invoices, and credits.","Produce a governed work order ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Vendor / Well Job","text","Vendor / Well Job · Standard Case"],["caseReference","Work order ingestion Reference","text","OST03-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1470000],["supportedAmount","Evidence-Supported Amount","currency",1234800],["domainDriver","Service Category","select","Drilling",["Drilling","Completion","Well service"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Master service agreement library case","Well job registry case","Work order ingestion case","Field ticket capture case","Crew hour validation case"]}),
feature("field-ticket-capture","OST04","Field ticket capture","Execute field ticket capture using master service agreements, wells, work orders, field tickets, crews, equipment, materials, rates, standby, mileage, invoices, and credits.","Produce a governed field ticket capture decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Vendor / Well Job","text","Vendor / Well Job · Standard Case"],["caseReference","Field ticket capture Reference","text","OST04-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1470000],["supportedAmount","Evidence-Supported Amount","currency",1234800],["domainDriver","Service Category","select","Drilling",["Drilling","Completion","Well service"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Master service agreement library case","Well job registry case","Work order ingestion case","Field ticket capture case","Crew hour validation case"]}),
feature("crew-hour-validation","OST05","Crew hour validation","Execute crew hour validation using master service agreements, wells, work orders, field tickets, crews, equipment, materials, rates, standby, mileage, invoices, and credits.","Produce a governed crew hour validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Vendor / Well Job","text","Vendor / Well Job · Standard Case"],["caseReference","Crew hour validation Reference","text","OST05-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1470000],["supportedAmount","Evidence-Supported Amount","currency",1234800],["domainDriver","Service Category","select","Drilling",["Drilling","Completion","Well service"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Master service agreement library case","Well job registry case","Work order ingestion case","Field ticket capture case","Crew hour validation case"]}),
feature("equipment-hour-validation","OST06","Equipment hour validation","Execute equipment hour validation using master service agreements, wells, work orders, field tickets, crews, equipment, materials, rates, standby, mileage, invoices, and credits.","Produce a governed equipment hour validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Vendor / Well Job","text","Vendor / Well Job · Standard Case"],["caseReference","Equipment hour validation Reference","text","OST06-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1470000],["supportedAmount","Evidence-Supported Amount","currency",1234800],["domainDriver","Service Category","select","Drilling",["Drilling","Completion","Well service"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Master service agreement library case","Well job registry case","Work order ingestion case","Field ticket capture case","Crew hour validation case"]}),
feature("material-quantity-matching","OST07","Material quantity matching","Execute material quantity matching using master service agreements, wells, work orders, field tickets, crews, equipment, materials, rates, standby, mileage, invoices, and credits.","Produce a governed material quantity matching decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Vendor / Well Job","text","Vendor / Well Job · Standard Case"],["caseReference","Material quantity matching Reference","text","OST07-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1470000],["supportedAmount","Evidence-Supported Amount","currency",1234800],["domainDriver","Service Category","select","Drilling",["Drilling","Completion","Well service"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Master service agreement library case","Well job registry case","Work order ingestion case","Field ticket capture case","Crew hour validation case"]}),
feature("rate-sheet-calculation","OST08","Rate sheet calculation","Execute rate sheet calculation using master service agreements, wells, work orders, field tickets, crews, equipment, materials, rates, standby, mileage, invoices, and credits.","Produce a governed rate sheet calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Vendor / Well Job","text","Vendor / Well Job · Standard Case"],["caseReference","Rate sheet calculation Reference","text","OST08-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1470000],["supportedAmount","Evidence-Supported Amount","currency",1234800],["domainDriver","Service Category","select","Drilling",["Drilling","Completion","Well service"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Master service agreement library case","Well job registry case","Work order ingestion case","Field ticket capture case","Crew hour validation case"]}),
feature("standby-time-audit","OST09","Standby time audit","Execute standby time audit using master service agreements, wells, work orders, field tickets, crews, equipment, materials, rates, standby, mileage, invoices, and credits.","Produce a governed standby time audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Vendor / Well Job","text","Vendor / Well Job · Standard Case"],["caseReference","Standby time audit Reference","text","OST09-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1470000],["supportedAmount","Evidence-Supported Amount","currency",1234800],["domainDriver","Service Category","select","Drilling",["Drilling","Completion","Well service"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Master service agreement library case","Well job registry case","Work order ingestion case","Field ticket capture case","Crew hour validation case"]}),
feature("mobilization-mileage","OST10","Mobilization mileage","Execute mobilization mileage using master service agreements, wells, work orders, field tickets, crews, equipment, materials, rates, standby, mileage, invoices, and credits.","Produce a governed mobilization mileage decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Vendor / Well Job","text","Vendor / Well Job · Standard Case"],["caseReference","Mobilization mileage Reference","text","OST10-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1470000],["supportedAmount","Evidence-Supported Amount","currency",1234800],["domainDriver","Service Category","select","Drilling",["Drilling","Completion","Well service"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Master service agreement library case","Well job registry case","Work order ingestion case","Field ticket capture case","Crew hour validation case"]}),
feature("fuel-surcharge-control","OST11","Fuel surcharge control","Execute fuel surcharge control using master service agreements, wells, work orders, field tickets, crews, equipment, materials, rates, standby, mileage, invoices, and credits.","Produce a governed fuel surcharge control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Vendor / Well Job","text","Vendor / Well Job · Standard Case"],["caseReference","Fuel surcharge control Reference","text","OST11-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1470000],["supportedAmount","Evidence-Supported Amount","currency",1234800],["domainDriver","Service Category","select","Drilling",["Drilling","Completion","Well service"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Master service agreement library case","Well job registry case","Work order ingestion case","Field ticket capture case","Crew hour validation case"]}),
feature("invoice-ticket-matching","OST12","Invoice ticket matching","Execute invoice ticket matching using master service agreements, wells, work orders, field tickets, crews, equipment, materials, rates, standby, mileage, invoices, and credits.","Produce a governed invoice ticket matching decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Vendor / Well Job","text","Vendor / Well Job · Standard Case"],["caseReference","Invoice ticket matching Reference","text","OST12-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1470000],["supportedAmount","Evidence-Supported Amount","currency",1234800],["domainDriver","Service Category","select","Drilling",["Drilling","Completion","Well service"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Master service agreement library case","Well job registry case","Work order ingestion case","Field ticket capture case","Crew hour validation case"]}),
feature("vendor-dispute-workflow","OST13","Vendor dispute workflow","Execute vendor dispute workflow using master service agreements, wells, work orders, field tickets, crews, equipment, materials, rates, standby, mileage, invoices, and credits.","Produce a governed vendor dispute workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Vendor / Well Job","text","Vendor / Well Job · Standard Case"],["caseReference","Vendor dispute workflow Reference","text","OST13-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1470000],["supportedAmount","Evidence-Supported Amount","currency",1234800],["domainDriver","Service Category","select","Drilling",["Drilling","Completion","Well service"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Master service agreement library case","Well job registry case","Work order ingestion case","Field ticket capture case","Crew hour validation case"]}),
feature("credit-reconciliation","OST14","Credit reconciliation","Execute credit reconciliation using master service agreements, wells, work orders, field tickets, crews, equipment, materials, rates, standby, mileage, invoices, and credits.","Produce a governed credit reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Vendor / Well Job","text","Vendor / Well Job · Standard Case"],["caseReference","Credit reconciliation Reference","text","OST14-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1470000],["supportedAmount","Evidence-Supported Amount","currency",1234800],["domainDriver","Service Category","select","Drilling",["Drilling","Completion","Well service"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Master service agreement library case","Well job registry case","Work order ingestion case","Field ticket capture case","Crew hour validation case"]}),
feature("well-vendor-analytics","OST15","Well vendor analytics","Execute well vendor analytics using master service agreements, wells, work orders, field tickets, crews, equipment, materials, rates, standby, mileage, invoices, and credits.","Produce a governed well vendor analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Vendor / Well Job","text","Vendor / Well Job · Standard Case"],["caseReference","Well vendor analytics Reference","text","OST15-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1470000],["supportedAmount","Evidence-Supported Amount","currency",1234800],["domainDriver","Service Category","select","Drilling",["Drilling","Completion","Well service"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Master service agreement library case","Well job registry case","Work order ingestion case","Field ticket capture case","Crew hour validation case"]})
]);
